# github.com/go-task/task

version: '3'

vars:
  BINARY_NAME: kubemq
  VERSION: v2.3.4

tasks:
  check_update:
    cmds:
      - go list -u -m -mod=mod -json all | go-mod-outdated -update -direct
  lint:
    cmds:
      - golangci-lint run --disable gocritic --enable misspell --disable gosec
  default:
    cmds:
      - go build -o "{{.BINARY_NAME}}.exe" -ldflags "-X 'main.version={{.VERSION}}'"
      - kubemq.exe server
  goreleaser:
    env:
      VERSION: v2.3.4
    cmds:
      - goreleaser --snapshot --skip-publish --rm-dist
  rundocker:
    cmds:
      - docker run -it --rm -p 8080:8080 -p 50000:50000 -p 9090:9090 kubemq/{{.BINARY_NAME}}-community:{{.VERSION}}
  docker:
    env:
      GOOS: linux
      GOARCH: amd64
    cmds:
      - docker build --build-arg VERSION={{.VERSION}} . -t kubemq/{{.BINARY_NAME}}-community:{{.VERSION}}
      - docker tag kubemq/{{.BINARY_NAME}}-community:{{.VERSION}} kubemq/{{.BINARY_NAME}}-community:latest
  release:
    cmds:
      - git tag -a {{.VERSION}} -m {{.VERSION}}
      - git push origin master --tags
