POST http://localhost:8080/api/request
Content-Type: application/json

{
    "type": "receive_queue_messages",
    "data": {
        "channel": "q",
        "isPeek": false,
        "count": 10
    }
}

###
