apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kubemq
  labels:
    app: kubemq
spec:
  replicas: 3
  selector:
    matchLabels:
      app: kubemq
  serviceName: "kubemq"
  template:
    metadata:
      labels:
        app: kubemq
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: kubemq
          image: kubemq/kubemq-community:latest
          imagePullPolicy: Always
          volumeMounts:
            - name: config-volume
              mountPath: ./kubemq/config
          ports:
            - name: grpc-port
              containerPort: 50000
              protocol: TCP
            - name: api-port
              containerPort: 8080
              protocol: TCP
            - name: rest-port
              containerPort: 9090
              protocol: TCP
      volumes:
        - name: config-volume
          configMap:
            name: kubemq-config
            items:
              - key: CONFIG
                path: config.yaml
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kubemq-config
data:
  CONFIG: |-
    api:
      port: 8080
      networkTransport: tcp
    authentication:
      config: ""
      enable: false
      jwtConfig:
        filePath: ""
        key: ""
        signatureType: ""
      type: ""
    authorization:
      autoReload: 0
      enable: false
      filePath: ""
      policyData: ""
      url: ""
    broker:
      diskSyncSeconds: 60
      maxConn: 0
      maxPayload: 104857600
      parallelRecovery: 2
      readBufferSize: 2
      sliceMaxAgeSeconds: 0
      sliceMaxBytes: 64
      sliceMaxMessages: 0
      writeBufferSize: 2
      writeDeadline: 2000
    grpc:
      bodyLimit: 104857600
      port: 50000
      networkTransport: tcp
      subBuffSize: 100
    log:
      level: info
    queue:
      defaultVisibilitySeconds: 60
      defaultWaitTimeoutSeconds: 1
      maxDelaySeconds: 43200
      maxExpirationSeconds: 43200
      maxInflight: 2048
      maxNumberOfMessages: 1024
      maxReceiveCount: 1024
      maxVisibilitySeconds: 43200
      maxWaitTimeoutSeconds: 3600
      pubAckWaitSeconds: 60
    rest:
      bodyLimit: ""
      cors:
        allowCredentials: false
        allowHeaders: []
        allowMethods:
          - GET
          - POST
        allowOrigins:
          - '*'
        exposeHeaders: []
        maxAge: 0
      port: 9090
      networkTransport: tcp
      readTimeout: 60
      subBuffSize: 100
      writeTimeout: 60
    routing:
      autoReload: 0
      data: ""
      enable: false
      filePath: ""
      url: ""
    security:
      ca:
        data: ""
        filename: ""
      cert:
        data: ""
        filename: ""
      key:
        data: ""
        filename: ""
    store:
      cleanStore: false
      maxMessages: 0
      maxPurgeInactive: 1440
      maxQueueSize: 0
      maxQueues: 0
      maxRetention: 1440
      maxSubscribers: 0
      storePath: ./store


---
apiVersion: v1
kind: Service
metadata:
  name: kubemq
spec:
  ports:
    - name: grpc-port
      protocol: TCP
      port: 50000
      targetPort: 50000
    - name: api-port
      protocol: TCP
      port: 8080
      targetPort: 8080
    - name: rest-port
      protocol: TCP
      port: 9090
      targetPort: 9090
  selector:
    app: kubemq
